export const staffData = [
  {
    id: "1",
    name: "Lee Chee Wah",
    name_zh: "李志华",
    role: "Headmaster",
    role_ms: "Guru Besar",
    role_zh: "校长",
    category: "Management",
    subject: ["Admin"],
    image: null,
    level: 0,
  },
  {
    id: "2",
    name: "Tan Siew Peng",
    name_zh: "陈秀萍",
    role: "Vice Principal (Admin)",
    role_ms: "GPK Pentadbiran",
    role_zh: "第一副校长",
    category: "Management",
    subject: ["Admin", "Mathematics"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "3",
    name: "Wong Siew Kee",
    name_zh: "王秀枝",
    role: "Vice Principal (Student Affairs)",
    role_ms: "GPK Hal Ehwal Murid",
    role_zh: "第二副校长",
    category: "Management",
    subject: ["Admin", "Moral"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "4",
    name: "Lim Ah Kow",
    name_zh: "林亚九",
    role: "Vice Principal (Co-curricular)",
    role_ms: "GPK Kokurikulum",
    role_zh: "第三副校长",
    category: "Management",
    subject: ["Admin", "Physical Education"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "5",
    name: "Chen Mei Ling",
    name_zh: "陈美玲",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["Chinese", "Music"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "6",
    name: "Zhang Wei",
    name_zh: "张伟",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["English", "Science"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "7",
    name: "Ahmad Bin Ismail",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["Malay"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "8",
    name: "Saraswathy A/P Mani",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["Mathematics", "Moral"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "9",
    name: "John Doe",
    role: "Staff",
    role_ms: "Staf Sokongan",
    role_zh: "行政人员",
    category: "Admin",
    subject: ["Admin"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "10",
    name: "Lim Mei Hua",
    name_zh: "林美华",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["Chinese", "Mathematics"],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "11",
    name: "Siti Aminah",
    role: "Teacher",
    role_ms: "Guru",
    role_zh: "老师",
    category: "Teacher",
    subject: ["Malay", "History"],
    parentId: "1",
    image: null,
    level: 1,
  },
];

export const subjects = [
  "Chinese",
  "English",
  "Malay",
  "Mathematics",
  "Science",
  "Music",
  "Physical Education",
  "Moral",
  "History",
  "Admin",
];
export const categories = ["Management", "Teacher", "Admin"];
