export const staffData = [
  {
    id: "1",
    name: "EN.CHONG CHEE BOON",
    name_zh: "张志文",
    role_ms: "Guru Besar",
    role_zh: "校长",
    category: "Management",
    subject: ["Admin"],
    image: null,
    level: 0,
  },
  {
    id: "2",
    name: "PN.LENG BEE LUAN",
    name_zh: "凌美鸾",
    role_ms: "Penolong Kanan Pentadbiran",
    role_zh: "行政管理副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "3",
    name: "PN.UWI SIU IAM",
    name_zh: "黄秀莹",
    role_ms: "Penolong Kanan Hal Ehwal Murid",
    role_zh: "学生事务副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "4",
    name: "PN.KOH YEAN INN",
    name_zh: "许艳茵",
    role_ms: "Penolong Kanan Kokurikulum",
    role_zh: "课外活动副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  }
];

export const subjects = [
  "Bahasa Cina",
  "Bahasa Inggeris",
  "Bahasa Melayu",
  "Matematik",
  "Sains",
  "Muzik",
  "Pendidikan Jasmani",
  "Pendidikan Seni",
  "Pendidikan Moral",
  "Pendidikan Islam",
  "Pendidikan Kesihatan",
  "Reka Bentuk dan Teknologi",
  "Sejarah",
  "Admin",
];
export const categories = ["Management", "Teacher", "Admin"];
