export const staffData = [
  {
    id: "1",
    name: "EN.CHONG CHEE BOON",
    name_zh: "张志文",
    role_ms: "Guru Besar",
    role_zh: "校长",
    category: "Management",
    subject: ["admin"],
    image: null,
    level: 0,
  },
  {
    id: "2",
    name: "PN.LENG BEE LUAN",
    name_zh: "凌美鸾",
    role_ms: "Penolong Kanan Pentadbiran",
    role_zh: "行政管理副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "3",
    name: "PN.UWI SIU IAM",
    name_zh: "黄秀莹",
    role_ms: "Penolong Kanan Hal Ehwal Murid",
    role_zh: "学生事务副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  },
  {
    id: "4",
    name: "PN.KOH YEAN INN",
    name_zh: "许艳茵",
    role_ms: "Penolong Kanan Kokurikulum",
    role_zh: "课外活动副校长",
    category: "Management",
    subject: [],
    parentId: "1",
    image: null,
    level: 1,
  },
];

export const subjects = [
  "bahasa_cina",
  "bahasa_inggeris",
  "bahasa_melayu",
  "matematik",
  "sains",
  "muzik",
  "pendidikan_jasmani",
  "pendidikan_seni",
  "pendidikan_moral",
  "pendidikan_islam",
  "pendidikan_kesihatan",
  "reka_bentuk_dan_teknologi",
  "sejarah",
  "admin",
];

export const categories = ["Management", "Teacher", "Admin"];
